[rabbitmq]
host = "10.229.54.16"

[api]
host = "0.0.0.0"
port = 8000
workers = 10

[suffix]
state_monitior = "State Monitor"

[rheed]
exchange = "RHEED"
exchange_type = "direct"

[rheed.pylon]
fps = 30
height = 540
width = 720
name = "Pylon Cam"
idle_time = 0.0033
queue_size = 2
camera_max_num_buffer = 15
exposure_time = 60000 # in the unit of us
gain = 240 # range from 0 to 240
gamma = 1.0 # range from 0 to 3.99
black_level = 0 # range from 0 to 511
auto_exposure = false
auto_gain = false
auto_aoi_intensity = false
auto_aoi_whitebalance = false

[rheed.webcam]
fps = 30
height = 480
width = 640
name = "Web Cam"
idle_time = 0.0033
queue_size = 2

[rheed.simcam]
fps = 30
height = 540
width = 720
source = "src/lumi/rheed/assets/test_frame.npy"
name = "Test Cam"
idle_time = 0.0033
queue_size = 2

exposure_time = 60000 # in units of μs
gain = 200 # ranges from 0 to 240
gamma = 1.0 # ranges from 0 to 3.99

is_base_oscillation = true
base_oscillation_frequency = 0.1
base_oscillation_amplitude = 100
is_feature_oscillation = true
feature_bbox = [100, 100, 620, 300]
feature_oscillation_frequency = 0.03
feature_oscillation_amplitude = 200
max_intensity = 4095

[rheed.video_compressor]
fps = 60
frames_per_keyframe = 1
fragment_queue_size = 60
cached_startup_fragments = 5
bit_rate = 12000000
name = "Video Compressor"

[rheed.video_recorder]
fps = 60
frames_per_keyframe = 10
bit_rate = 12000000

[rheed.stft_calculator]
idle_time = 0.005
output_queue_size = 50
window_size = 240
hop_size = 1
time_resolution = 0.1
frequency_min = 0
frequency_max = 1

[rheed.integrator]
idle_time = 0.005
output_queue_size = 50

[rheed.mq.live_video]
ctrl_key = "live_video_ctrl"
publish_key = "live_video"
state_key = "live_video_state"
name = "Live RHEED Video"
state_monitor_name = "Live RHEED Cam Monitor"

[rheed.mq.video]
ctrl_key = "video_ctrl"
request_key = "video"
state_key = "video_state"
name = "RHEED Video"

[rheed.mq.camera]
request_key = "camera"
ctrl_key = "camera_ctrl"
state_key = "camera_state"
name = "RHEED Camera"

[rheed.mq.live_camera]
ctrl_key = "live_camera_ctrl"
publish_key = "live_camera"
state_key = "live_camera_state"
name = "Live RHEED Camera"
state_monitor_name = "Live RHEED Camera Monitor"

[rheed.mq.live_integrator]
ctrl_key = "live_integrator_ctrl"
publish_key = "live_integrator"
state_key = "live_integrator_state"
name = "Live RHEED Integrator"
state_monitor_name = "Live RHEED Integrator Monitor"

[rheed.mq.integrator]
request_key = "integrator"
ctrl_key = "integrator_ctrl"
state_key = "integrator_state"
name = "RHEED Integrator"

[rheed.mq.live_stft]
ctrl_key = "live_stft_ctrl"
publish_key = "live_stft"
state_key = "live_stft_state"
name = "Live RHEED STFT"
state_monitor_name = "Live RHEED STFT Monitor"

[rheed.mq.stft]
request_key = "stft"
ctrl_key = "stft_ctrl"
state_key = "stft_state"
name = "RHEED STFT"

[detection]
exchange = "RHEED"
exchange_type = "direct"

[detection.detector]
input_queue_size = 10
output_queue_size = 10
model_device = "cuda:3"
model_folder = "/home/hliang16/projects/RHEEDDetector/nn/cascade_maskrcnn_exps_Feb272025"
name = "Detector"

[detection.detector.crop_setup]
sx = 0
sy = 0
ex = 540
ey = 720

[detection.mq.detection]
request_key = "detection"
ctrl_key = "detection_ctrl"
state_key = "detection_state"
name = "RHEED Detection"

[detection.mq.live_detection]
publish_key = "live_detection"
ctrl_key = "live_detection_ctrl"
state_key = "live_detection_state"
name = "Live RHEED Detection"
state_monitor_name = "Live RHEED Detection Monitor"

[pascal]
exchange = "CHAMBER"
exchange_type = "direct"
mi_mode_folder = "mi_mode"
chamber_log_folder = "chamber_log"

[pascal.config_reader.test]
idle_time = 0.1
config_path = "src/lumi/pascal/assets/PLDconfig_07102025.ini"
name = "test_config_reader"

[pascal.config_reader]
idle_time = 0.1
config_path = "C:/Program Files (x86)/PLD Controller/PLDconfig.ini"
name = "config_reader"

[pascal.log_reader]
idle_time = 0.01
queue_size = 10
name = "log_reader"

[pascal.log_reader.test]
idle_time = 0.01
queue_size = 10
publish_interval = 1
log_file = "chamber_log_test.csv"
name = "test_log_reader"

[pascal.mi_mode_server]
queue_size = 1000
idle_time = 0.01
assist_file_name = "assist.txt"
name = "mi_mode_server"

[pascal.mq.chamber_log]
request_key = "chamber_log"
ctrl_key = "chamber_log_ctrl"
state_key = "chamber_log_state"
name = "Chamber Log"

[pascal.mq.chamber_config]
request_key = "chamber_config"
ctrl_key = "chamber_config_ctrl"
state_key = "chamber_config_state"
name = "Chamber Config"

[pascal.mq.live_chamber_log]
publish_key = "live_chamber_log"
ctrl_key = "live_chamber_log_ctrl"
state_key = "live_chamber_log_state"
name = "Live Chamber Log"
state_monitor_name = "Live Chamber Log Monitor"

[pascal.mq.mi_mode]
request_key = "mi_mode_request"
response_key = "mi_mode_response"
update_key = "mi_mode_update"
ctrl_key = "mi_mode_ctrl"
state_key = "mi_mode_state"
name = "MI Mode"
state_monitor_name = "MI Mode Monitor"

[storage]
exchange = "STORAGE"
exchange_type = "direct"

[storage.databases]
log = "log"

frame = "frame"
frame_meta = "frame_meta"

integration = "integration"
integration_root = "integration_root"
integration_meta = "integration_meta"

pattern = "pattern"
classification = "classification"
detection = "detection"
instance_segmentation = "instance_segmentation"
num_detection = "num_detection"

tracking = "tracking"
num_tracking = "num_tracking"

detection_meta = "detection_meta"


[storage.hdf5_recorder]
idle_time = 0.01
max_workers = 8
database_path = "database"
initial_size = 1000

[storage.hdf5_recorder.buffer]
intergration_buffer_size = 10

[storage.mq.storage]
request_key = "storage"
ctrl_key = "storage_ctrl"
state_key = "storage_state"
name = "Storage"
