"""Shared helpers for the emitters."""

from __future__ import annotations

from pydantic import BaseModel

from lumi.contracts import Capability, Codec, EquipmentContract, contract_hash

BANNER = """\
# AUTOGENERATED by `uv run lumi-codegen` from lumi.contracts -- DO NOT EDIT.
#
# Every method below is derived from a single declaration in src/lumi/contracts/.
# Editing this file by hand will be overwritten, and `lumi-codegen --check` (which
# CI runs) will fail. Change the contract instead.
#
# contract_hash: {hash}
"""

TS_BANNER = """\
// AUTOGENERATED by `uv run lumi-codegen` from lumi.contracts -- DO NOT EDIT.
//
// contract_hash: {hash}
"""


def banner() -> str:
    return BANNER.format(hash=contract_hash())


def ts_banner() -> str:
    return TS_BANNER.format(hash=contract_hash())


def pascal(name: str) -> str:
    """rheed.camera -> RheedCamera; live_camera -> LiveCamera."""
    return "".join(part.capitalize() for part in name.replace(".", "_").split("_"))


def client_class(equipment: str, capability: str) -> str:
    return f"{pascal(equipment)}{pascal(capability)}Client"


def models_of(cap: Capability) -> list[type[BaseModel]]:
    """Every model a capability's generated client needs to name."""
    out: list[type[BaseModel]] = [cap.state]
    for op in cap.ops:
        out += [op.request, op.response]
    for spec in (cap.stream, cap.update):
        if spec is not None:
            out.append(spec.payload)
    return out


def all_models(contract: EquipmentContract) -> list[type[BaseModel]]:
    seen: dict[str, type[BaseModel]] = {}
    for cap in contract.capabilities:
        for model in models_of(cap):
            seen[model.__name__] = model
    return [seen[k] for k in sorted(seen)]


def import_block(models: list[type[BaseModel]]) -> str:
    """Group model imports by the module they live in."""
    by_module: dict[str, set[str]] = {}
    for model in models:
        by_module.setdefault(model.__module__, set()).add(model.__name__)
    lines = []
    for module in sorted(by_module):
        names = ", ".join(sorted(by_module[module]))
        lines.append(f"from {module} import {names}")
    return "\n".join(lines)


def payload_type(codec: Codec) -> str:
    """What the binary half of a response is, if there is one."""
    if codec is Codec.NPY:
        return "np.ndarray"
    if codec is Codec.NPZ:
        return "dict[str, np.ndarray]"
    if codec is Codec.RAW:
        return "bytes"
    return ""


def return_type(model: type[BaseModel], codec: Codec) -> str:
    binary = payload_type(codec)
    return f"tuple[{model.__name__}, {binary}]" if binary else model.__name__
